### ISSUE TITLE
Extra endpoints

### ISSUE THREAD

**Issue by GashinRS** [SELab-2/Dr-Trottoir-4#223]
**Extra endpoints for the frontend**:
- [x]  Add an endpoint for `StudentOnTour` which can be used to retrieve filtered data. The necessary parameters are: `start date` and `end date`, `student`, `tour`, `region`. Filtering this data in the backend is more efficient as the alternative option would be to fetch all data in the frontend and filter them which is a lot of overhead (#219).
- [x] Add an endpoint for `GarbageCollection` which can be used to retrieve the garbage collection for a building on a specific date (#220).
- [x] Add an endpoint for `GarbageCollection` which can be used to duplicate the garbage collections of the previous two weeks. The garbage collections will stay mostly the same between weeks so it's more efficient to just duplicate past garbage collections and make changes where needed instead of inputting everything all over again (#221).
- [ ] Add an endpoint for fetching all syndics and non syndics. This is necessary because when selecting who can do tours, we only want non syndics to show up. On the other hand, when selecting a building's syndic we only want to see syndics as the possible choices (#246)
